# Generated by Django 3.2 on 2023-03-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email", "username"), name="unique_pair"
            ),
        ),
    ]
