# Generated by Django 3.2 on 2023-03-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_user_unique_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "Авторизованный пользователь"),
                    ("moderator", "Модератор"),
                    ("admin", "Администратор"),
                ],
                max_length=10,
                verbose_name="Пользовательская роль",
            ),
        ),
    ]
